name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Deploy to PythonAnywhere
        env:
          PA_USERNAME: ${{ secrets.PA_USERNAME }}
        run: |
          echo "Setting up SSH"
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ssh.pythonanywhere.com >> ~/.ssh/known_hosts
          ssh $PA_USERNAME@ssh.pythonanywhere.com <<EOF
          cd /home/$PA_USERNAME/VC-Resource-Center
          git pull origin master
          workon .venv-3.10
          pip install -r requirements.txt
          # python manage.py migrate  # Execute database migrations if needed
          touch /var/www/www_$PA_USERNAME_org_wsgi.py  # Touch the WSGI file to reload the app
          EOF

